enabled_locales: ['en', 'vi']
validation:
  max_length: 255
  name_length: 50
  passw_minl: 6
gravatar_size: 80
gravater_small_size: 30
users:
  per_page: 10
  thumb_size: 50
microposts:
  content_max_length: 140
  per_page: 10
  picture_capacity: 5
  picture_width: 400
  picture_height: 400
feed:
  per_page: 5
remember_me: 1
reset_expired: 2
